# Generated by Django 3.0.5 on 2023-10-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20231021_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='Patient',
        ),
    ]
